name: fifamanager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3

  confetti: ^0.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

# ─── Configuração do ícone do app ───────────────────────────────────────────
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

# ────────────────────────────────────────────────────────────────────────────
flutter:
  uses-material-design: true

  assets:
    - assets/splash_bg_new.png
    - assets/login_bg.png
    - assets/splash_bg.png
    - assets/trophy-A.png
    - assets/trophy-B.png
    - assets/trophy-CUP.png
    - assets/app_icon.png
    - assets/shirt.png
    - assets/TacticalBoard.png
